const SET_CASES = 'SET_CASES';
const SET_VACCINES = 'SET_VACCINES';
const SET_LOADING_CASES = 'SET_LOADING_CASES';
const SET_LOADING_GLOBAL = 'SET_LOADING_GLOBAL';
const SET_COUNTRIES = 'SET_COUNTRIES';
const SET_GLOBALS = 'SET_GLOBALS';
const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';

export default {
  SET_CASES,
  SET_VACCINES,
  SET_LOADING_CASES,
  SET_COUNTRIES,
  SET_GLOBALS,
  SET_LOADING_GLOBAL,
  SET_SELECTED_COUNTRY,
};
