const GET_CASES = 'GET_CASES';
const SET_LOADING_CASES = 'SET_LOADING_CASES';
const SET_COUNTRIES = 'SET_COUNTRIES';
const SET_GLOBALS = 'SET_GLOBALS';

export default { GET_CASES, SET_LOADING_CASES, SET_COUNTRIES, SET_GLOBALS };
