const SET_CASES = 'SET_CASES';
const SET_VACCINES = 'SET_VACCINES';
const SET_LOADING_DATA = 'SET_LOADING_DATA';
const SET_LOADING_GLOBAL = 'SET_LOADING_GLOBAL';
const SET_COUNTRIES = 'SET_COUNTRIES';
const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';

export default {
  SET_CASES,
  SET_VACCINES,
  SET_LOADING_DATA,
  SET_COUNTRIES,
  SET_LOADING_GLOBAL,
  SET_SELECTED_COUNTRY,
};
